#spring
spring:
  application:
    name: system-user-consumer
  thymeleaf:
    suffix: .html
    cache: false
    mode: LEGACYHTML5
#server
server:
  port: 9301
#dubbo
dubbo:
  application:
    id: system-user-consumer
    name: system-user-consumer
    owner: songmj
#服务注册配置
  registry:
    id: kpi-dubbo
    address: zookeeper://localhost:2181
#dubbo健康监控
management:
  port: 9401
#启动日志
#debug: true
